"""add_cascade_delete_to_highlights_user_fk

Revision ID: 0618711d3113
Revises: 98420816343a
Create Date: 2026-03-01 22:16:04.158555

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "0618711d3113"
down_revision: Union[str, Sequence[str], None] = "98420816343a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("highlights_user_id_fkey"), "highlights", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "highlights", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "highlights", type_="foreignkey")
    op.create_foreign_key(
        op.f("highlights_user_id_fkey"), "highlights", "users", ["user_id"], ["id"]
    )
    # ### end Alembic commands ###
