"""add tags to content items

Revision ID: 18e333bfc270
Revises: a9b3f8ba83df
Create Date: 2026-01-13 22:46:48.642663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18e333bfc270'
down_revision: Union[str, Sequence[str], None] = 'a9b3f8ba83df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_items', sa.Column('tags', sa.ARRAY(sa.String(length=100)), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content_items', 'tags')
    # ### end Alembic commands ###
