"""initial schema with users, content_items, and lists

Revision ID: 43acce7f6578
Revises:
Create Date: 2026-01-09 23:56:50.193176

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = "43acce7f6578"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "content_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("original_url", sa.Text(), nullable=False),
        sa.Column("submitted_via", sa.String(length=50), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("thumbnail_url", sa.Text(), nullable=True),
        sa.Column("content_type", sa.String(length=50), nullable=True),
        sa.Column("author", sa.String(length=255), nullable=True),
        sa.Column("published_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("full_text", sa.Text(), nullable=True),
        sa.Column("word_count", sa.Integer(), nullable=True),
        sa.Column("reading_time_minutes", sa.Integer(), nullable=True),
        sa.Column("embedding", Vector(1536), nullable=True),
        sa.Column("is_read", sa.Boolean(), nullable=True),
        sa.Column("is_archived", sa.Boolean(), nullable=True),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("processing_status", sa.String(length=50), nullable=True),
        sa.Column("processing_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_content_items_content_type"),
        "content_items",
        ["content_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_content_items_created_at"),
        "content_items",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_content_items_deleted_at"),
        "content_items",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_content_items_is_archived"),
        "content_items",
        ["is_archived"],
        unique=False,
    )
    op.create_index(
        op.f("ix_content_items_is_read"), "content_items", ["is_read"], unique=False
    )
    op.create_index(
        op.f("ix_content_items_processing_status"),
        "content_items",
        ["processing_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_content_items_user_id"), "content_items", ["user_id"], unique=False
    )
    op.create_table(
        "lists",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("is_shared", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_lists_owner_id"), "lists", ["owner_id"], unique=False)
    op.create_table(
        "content_list_membership",
        sa.Column("content_item_id", sa.UUID(), nullable=False),
        sa.Column("list_id", sa.UUID(), nullable=False),
        sa.Column(
            "added_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("added_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["added_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["content_item_id"], ["content_items.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["list_id"], ["lists.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("content_item_id", "list_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("content_list_membership")
    op.drop_index(op.f("ix_lists_owner_id"), table_name="lists")
    op.drop_table("lists")
    op.drop_index(op.f("ix_content_items_user_id"), table_name="content_items")
    op.drop_index(
        op.f("ix_content_items_processing_status"), table_name="content_items"
    )
    op.drop_index(op.f("ix_content_items_is_read"), table_name="content_items")
    op.drop_index(op.f("ix_content_items_is_archived"), table_name="content_items")
    op.drop_index(op.f("ix_content_items_deleted_at"), table_name="content_items")
    op.drop_index(op.f("ix_content_items_created_at"), table_name="content_items")
    op.drop_index(op.f("ix_content_items_content_type"), table_name="content_items")
    op.drop_table("content_items")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
