"""Refactor is_academic to vertical_metadata jsonb

Revision ID: 4e5abe77d033
Revises: 007_add_status
Create Date: 2026-02-23 12:35:58.740692

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4e5abe77d033"
down_revision: Union[str, Sequence[str], None] = "007_add_status"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "content_items",
        sa.Column(
            "content_vertical",
            sa.String(length=50),
            server_default="general",
            nullable=True,
        ),
    )
    op.add_column(
        "content_items",
        sa.Column(
            "vertical_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=True,
        ),
    )
    op.create_index(
        op.f("ix_content_items_content_vertical"),
        "content_items",
        ["content_vertical"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_content_items_content_vertical"), table_name="content_items")
    op.drop_column("content_items", "vertical_metadata")
    op.drop_column("content_items", "content_vertical")
    # ### end Alembic commands ###
