"""add_public_profile_fields

Revision ID: 61fab174e21e
Revises: 4e5abe77d033
Create Date: 2026-02-23 20:27:35.712200

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "61fab174e21e"
down_revision: Union[str, Sequence[str], None] = "4e5abe77d033"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "content_items",
        sa.Column(
            "is_public", sa.Boolean(), server_default=sa.text("false"), nullable=True
        ),
    )
    op.create_index(
        op.f("ix_content_items_is_public"), "content_items", ["is_public"], unique=False
    )
    op.add_column(
        "lists",
        sa.Column(
            "is_public", sa.Boolean(), server_default=sa.text("false"), nullable=True
        ),
    )
    op.create_index(op.f("ix_lists_is_public"), "lists", ["is_public"], unique=False)
    op.add_column("users", sa.Column("username", sa.String(length=50), nullable=True))
    op.add_column(
        "users",
        sa.Column(
            "is_public", sa.Boolean(), server_default=sa.text("false"), nullable=True
        ),
    )
    op.create_index(op.f("ix_users_is_public"), "users", ["is_public"], unique=False)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.add_column(
        "vinyl_records",
        sa.Column(
            "is_public", sa.Boolean(), server_default=sa.text("false"), nullable=True
        ),
    )
    op.create_index(
        op.f("ix_vinyl_records_is_public"), "vinyl_records", ["is_public"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_vinyl_records_is_public"), table_name="vinyl_records")
    op.drop_column("vinyl_records", "is_public")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_is_public"), table_name="users")
    op.drop_column("users", "is_public")
    op.drop_column("users", "username")
    op.drop_index(op.f("ix_lists_is_public"), table_name="lists")
    op.drop_column("lists", "is_public")
    op.drop_index(op.f("ix_content_items_is_public"), table_name="content_items")
    op.drop_column("content_items", "is_public")
    # ### end Alembic commands ###
