"""add vinyl records table

Revision ID: 6ea16ce5c4b6
Revises: 004_cascade_delete
Create Date: 2026-02-09 13:22:03.115207

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6ea16ce5c4b6"
down_revision: Union[str, Sequence[str], None] = "004_cascade_delete"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vinyl_records",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("discogs_url", sa.Text(), nullable=False),
        sa.Column("discogs_release_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("artist", sa.Text(), nullable=True),
        sa.Column("label", sa.String(length=255), nullable=True),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("cover_url", sa.Text(), nullable=True),
        sa.Column("genres", sa.ARRAY(sa.String(length=100)), nullable=True),
        sa.Column("styles", sa.ARRAY(sa.String(length=100)), nullable=True),
        sa.Column("tracklist", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("rating", sa.Integer(), nullable=True),
        sa.Column("tags", sa.ARRAY(sa.String(length=100)), nullable=True),
        sa.Column("processing_status", sa.String(length=50), nullable=True),
        sa.Column("processing_error", sa.Text(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_vinyl_records_created_at"),
        "vinyl_records",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_vinyl_records_deleted_at"),
        "vinyl_records",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_vinyl_records_discogs_release_id"),
        "vinyl_records",
        ["discogs_release_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_vinyl_records_processing_status"),
        "vinyl_records",
        ["processing_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_vinyl_records_user_id"), "vinyl_records", ["user_id"], unique=False
    )
    op.drop_index(op.f("ix_content_items_read_position"), table_name="content_items")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_content_items_read_position"),
        "content_items",
        ["read_position"],
        unique=False,
    )
    op.drop_index(op.f("ix_vinyl_records_user_id"), table_name="vinyl_records")
    op.drop_index(
        op.f("ix_vinyl_records_processing_status"), table_name="vinyl_records"
    )
    op.drop_index(
        op.f("ix_vinyl_records_discogs_release_id"), table_name="vinyl_records"
    )
    op.drop_index(op.f("ix_vinyl_records_deleted_at"), table_name="vinyl_records")
    op.drop_index(op.f("ix_vinyl_records_created_at"), table_name="vinyl_records")
    op.drop_table("vinyl_records")
    # ### end Alembic commands ###
