"""Add specific queue and crates visibility toggles to User

Revision ID: c91ada885da7
Revises: 61fab174e21e
Create Date: 2026-02-24 14:00:49.143033

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c91ada885da7"
down_revision: Union[str, Sequence[str], None] = "61fab174e21e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("is_queue_public", sa.Boolean(), nullable=True))
    op.add_column("users", sa.Column("is_crates_public", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_crates_public")
    op.drop_column("users", "is_queue_public")
    # ### end Alembic commands ###
